#!/bin/sh
rm -f src/*.o
rm -f src/*.mod
rm -f src/*.dll
rm -f src/libed2.a
rm -f src/*.so
rm -f src/Makevars
rm -f src/Makevars.ucrt
rm -f src/edmain*
rm -rf inst/bin
rm -f config.*
rm -f configure~
rm -f aclocal.m4
find src -type f -name "*.mod" -delete
find src -type f -name "*.o" -delete
